### ISSUE TITLE
Not able to register individual on staging

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1648]
**Describe the bug**
Not able to register individual on staging
Login with acha@testjsscp
try to register the individual I am not able to go next page

**To Reproduce**
1. acha@testjsscp
2. click on register individual 
3. fill the form 
4. not able to go summary page

**Screenshots**

https://github.com/user-attachments/assets/906f7606-e924-42c9-b03a-9a0372e08ea4

I am using this apk 
https://app.circleci.com/pipelines/github/avniproject/avni-client/2870/workflows/0f14e755-a615-41cc-9e30-31aff759311d/jobs/18780

**Comment by mahalakshme** [comment]
@AchalaBelokar the above is not happening on 12.2 no?

**Comment by AchalaBelokar** [comment]
@mahalakshme it is working fine on 12.2

**Comment by 1t5j0y** [comment]
Old style rules from the bundle on this org seem to be returning old FormElementStatus elements for Question Group form elements causing a `formElementStatus.addQuestionGroupInformation is not a function (it is undefined)` error.

Issue is occurring on older versions of client and DEA as well.

Looks like this a test environment configuration and not intended to be supported. Let me know if this needs to be looked into further.

FYI @mahalakshme / @AchalaBelokar

**Comment by mahalakshme** [comment]
The old rule didnt work with Question group added. But in actual form there is no question group. Without that works fine. So closing this.
